config/routes.rb
Rails.application.routes.draw do
  resources :grupos
  resources :riesgos
  resources :categoria_riesgos
  resources :impacto_riesgos
  resources :tipo_proyectos
  resources :proyectos
  resources :usuarios
  
  root 'pages#home'
  post 'login' => 'pages#login'
  post 'recuperarPass' => 'pages#recuperarPass'
  get 'recuperar' => 'pages#recuperar'
  get 'correo'=> 'pages#correo'
  get 'registrarse' => 'pages#registrar'
  get 'salir' => 'pages#salir'
  get 'delTipoProyecto/:id'=> 'tipo_proyectos#destroy', as: :delTipoProyecto
  get 'delCategoriaRiesgos/:id'=> 'categoria_riesgos#destroy', as: :delCategoriaRiesgos
  get 'delImpactoRiesgos/:id'=> 'impacto_riesgos#destroy', as: :delImpactoRiesgos
  get 'delRiesgo/:id'=> 'riesgos#destroy', as: :delRiesgo
  get 'delProyecto/:id'=> 'proyectos#destroy', as: :delProyecto
  get 'subir' => 'proyectos#lineaCorteUp'
  get 'bajar' => 'proyectos#lineaCorteDown'
  get 'estadisticas' => 'pages#estadisticas'
  get 'add/:id'=>'riesgos#add', as: :addRiesgo
  get 'nuevoProyecto/:id'=> 'proyectos#new', as: :nuevoProyecto
  get 'delGrupo/:id'=> 'grupos#destroy', as: :delGrupo
  get 'addUserToGroup/:id'=>'pages#addUserToGroup', as: :addUserToGroup
  post 'addtog'=> 'pages#addtog'
  get 'darPermisos/:igu/:iu'=> 'pages#darPermisos', as: :darPermisos
  get 'quitarPermisos/:igu/:iu'=> 'pages#quitarPermisos', as: :quitarPermisos
  get 'del_user_grupo/:igu/:iu' => 'pages#del_user_grupo', as: :del_user_grupo
  get '*path' => redirect('/')

end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
  
  validates :nombre ,:tipo , :descripcion ,presence:true
  
  validates :nombre, length: { in: 1..255 , message: "debe tener entre 1 y 255 caracteres"}
  validates :tipo, length: { in: 1..255 , message: "debe tener entre 1 y 255 caracteres"}
  validates :descripcion, length: { in: 1..255 , message: "debe tener entre 1 y 255 caracteres"}
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
 before_action :require_login
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy]

  def require_login
     current_user
    unless @current_user!=nil
      redirect_to root_path
    end
  end
  # GET /proyectos
  # GET /proyectos.json
  def index
    current_user
    current_grupo
    @proyectos = Proyecto.all
     @tipo_proyectos = TipoProyecto.all
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
     @tipo_proyectos = TipoProyecto.all
    current_user
    current_grupo
    proyecto @proyecto.id
    current_proyecto
     @riesgos = Riesgo.all
     pr=Proyecto.find(@current_proyecto)
     @lineaCorte=pr.lineaCorte
  end
  
   def lineaCorteUp
    current_user
    current_proyecto
    @proyec=Proyecto.find(@current_proyecto)
    @proyec.lineaCorte=@proyec.lineaCorte.to_i-1
    @proyec.save
    current_grupo
    redirect_to @proyec
    
  end
  
  def lineaCorteDown
    current_user
    current_proyecto
     @proyec=Proyecto.find(@current_proyecto)
    @proyec.lineaCorte=@proyec.lineaCorte.to_i+1
    @proyec.save
    current_grupo
    redirect_to @proyec
  end
  
  def numeric(s)
    Float(s) != nil rescue false
  end
  # GET /proyectos/new
  def new
    current_user
    
    if !numeric(params[:id])
        redirect_to proyectos_path
      else
        if Grupo.all.where(:idUsuario=> @current_user["id"]).where(:idGrupoUsuario=>params[:id]).count>0
          grupo(params[:id])
          current_grupo
          @proyecto = Proyecto.new
          @tipo_proyectos = TipoProyecto.all
      else
        redirect_to proyectos_path
      end
      end
    
  end

  # GET /proyectos/1/edit
  def edit
    current_user
    current_grupo
     @tipo_proyectos = TipoProyecto.all
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
     @tipo_proyectos = TipoProyecto.all
    current_user
    current_grupo
    @proyecto = Proyecto.new(proyecto_params)
    @proyecto.idUsuario= @current_grupo
    if numeric(@proyecto.tipo)
    @proyecto.tipo=TipoProyecto.find(@proyecto.tipo).nombre
    end
    @proyecto.lineaCorte=1
    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: '' }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
     @tipo_proyectos = TipoProyecto.all
    current_user
    current_grupo
    respond_to do |format|
       proyecto=proyecto_params
      if numeric(proyecto[:tipo])
   proyecto[:tipo]=TipoProyecto.find(proyecto_params[:tipo])[:nombre]
   end
      if @proyecto.update(proyecto)
        format.html { redirect_to @proyecto, notice: '' }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
     @tipo_proyectos = TipoProyecto.all
    @proyecto.destroy
    current_user
    current_grupo
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: 'Proyecto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
       current_user
       current_grupo
      if !numeric(params[:id])
        redirect_to root_path
      else
        aux=0
        Grupo.all.where(:idUsuario=> @current_user["id"]).each do |grupo|
        if Proyecto.all.where(:idUsuario=>grupo.idGrupoUsuario).where(:id=>params[:id]).count>0
          @proyecto = Proyecto.find(params[:id])
          aux=1
      end
      end
      if aux==0
        redirect_to root_path
      end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyecto_params
      params.require(:proyecto).permit(:nombre, :tipo, :descripcion, :inicio, :fin, :idUsuario)
    end
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/proyectos/_form.html.erb
<%= form_for(@proyecto,:html=>{:onsubmit=>"return validacionProyecto();"}) do |f| %>
  <% if @proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% @proyecto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <style>
select#proyecto_inicio_1i {
  display: inline;
  width: auto;
    height: 30px;
    padding: 0;
}
select#proyecto_inicio_2i {
  display: inline;
  width: auto;
   height: 30px;
    padding: 0;
}
select#proyecto_inicio_3i {
  display: inline;
  width: auto;
   height: 30px;
    padding: 0;
}
select#proyecto_fin_1i {
  display: inline;
  width: auto;
   height: 30px;
    padding: 0;
}
select#proyecto_fin_2i {
  display: inline;
  width: auto;
   height: 30px;
    padding: 0;
}
select#proyecto_fin_3i {
  display: inline;
  width: auto;
   height: 30px;
    padding: 0;
}
form select{
	 height: 30px;
    padding: 0;
}

  </style>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, :onkeyup=>"notNull(this);" %>
  </div>
  <div class="field">
    <label for="proyecto_tipo">Tipo  <i class="fa fa-plus-circle fa-2x" onclick="document.getElementById('proyecto_tipo').disabled=false;if(document.getElementById('add').style.display=='block'){document.getElementById('add').style.display='none'}else{document.getElementById('add').style.display='block';document.getElementById('edit').style.display='none';}">
  
    </i> <i class="fa fa-pencil-square-o fa-2x" onclick="if(document.getElementById('proyecto_tipo').value!='Seleccione un tipo'){document.getElementById('edit').src='/tipo_proyectos/'+document.getElementById('proyecto_tipo').value+'/edit'};if(document.getElementById('proyecto_tipo').value!='Seleccione un tipo'){if(document.getElementById('edit').style.display=='block'){document.getElementById('edit').style.display='none';document.getElementById('proyecto_tipo').disabled=false;}else{document.getElementById('edit').style.display='block';document.getElementById('add').style.display='none';document.getElementById('proyecto_tipo').disabled=true;}};"></i> 
    <i class="fa fa-times fa-2x" onclick="document.getElementById('proyecto_tipo').disabled=false;if(document.getElementById('proyecto_tipo').value!='Seleccione un tipo'){document.getElementById('add').style.display='none';document.getElementById('edit').style.display='none';$.ajax({
  url: '/delTipoProyecto/'+document.getElementById('proyecto_tipo').value});var x = document.getElementById('proyecto_tipo');
    x.options[x.selectedIndex] =null};"></i></label> 
    
    <iframe id="add" src="<%=new_tipo_proyecto_path%>" style="display:none;position: fixed; z-index: 99; background-color: rgba(172,220,218,1);border: solid 2px;border-radius: 20px;"></iframe><br>
    
    <iframe id="edit" src="" style="display:none;position: fixed; z-index: 99; background-color: rgba(172,220,218,1);border: solid 2px;border-radius: 20px;"></iframe><br>
    
    <select name="proyecto[tipo]" id="proyecto_tipo" onclick="notNull(this);">
  <%= content_tag(:option, "Seleccione un tipo", value: "Seleccione un tipo") %>
  
  <% @tipo_proyectos.where(:idUsuario=>Grupo.all.select(:idGrupoUsuario).where(:idUsuario=>@current_user["id"])).group(:nombre).each do |tipo_proyecto|%>
  
  <%if @proyecto.tipo.eql? tipo_proyecto.nombre%>
    <%= content_tag(:option, tipo_proyecto.nombre, value: tipo_proyecto.id, selected: true) %>
    <%else%>
    <%= content_tag(:option, tipo_proyecto.nombre, value: tipo_proyecto.id) %>
    <%end%>
    
  <% end %>
</select>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion, :onkeyup=>"notNull(this);" %>
  </div>
  <div class="field">
    <%= f.label :inicio %><br>
    <%= f.date_select :inicio, :order => [:day, :month, :year], use_two_digit_numbers: true %>
  </div>
  <div class="field">
    <%= f.label :fin %><br>
    <%= f.date_select :fin, :order => [:day, :month, :year], use_two_digit_numbers: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>Web de administracion y gestion de riesgos | Proyecto</title>
		<% user @current_user %>
	</head>
	<body>
		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

							<header>
								<h2 class="alt">Editando el Proyeto <%= @proyecto.id %>.</h2>
							</header>
						</div>
					</section>

				<!-- Portfolio -->
					<section id="top" class="two">
						<div class="container">
							<%= render 'form' %>

<%= link_to 'Show', @proyecto %> |
<%= link_to 'Back', proyectos_path %>

</div>
					</section>

			</div>

	</body>
</html>

app/views/proyectos/index.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>Web de administracion y gestion de riesgos | inicio</title>
		<% user @current_user %>
	</head>
	<body>
		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

							<header>
								<h2 class="alt">Lista de proyectos de <%=@current_user["alias"]%></h2>
							</header>
						</div>
					</section>
					
		<p style="text-align: center;"><a href="<%=new_grupo_path%>" ><i class="fa fa-plus-circle fa-2x"></i>Añadir grupo.</a> </p>
<% Grupo.all.where(:idUsuario=>@current_user["id"]).each do |grupo|%>
				<!-- Portfolio -->
					<section id="top" class="two">
						<div class="container">
							<%if grupo.admin=="true"%>
					<p style="text-align: right;"><a href="<%=delGrupo_path(grupo.idGrupoUsuario)%>"><i class="fa fa-times fa-2x"></i>Eliminar</a></p>	
								<%end%>
<p style="font-size: large;">Grupo <%=grupo["nombre"]%>.</p>
<p>Miembros:<br />
	<%Grupo.all.where(:idGrupoUsuario=>grupo.idGrupoUsuario).each do |user|%>
	<%if user.admin=="false" or user.admin=="tru"%>
	<a href="<%=del_user_grupo_path(:igu=>grupo.idGrupoUsuario,:iu=>user.idUsuario)%>"><i class="fa fa-times fa-1x"></i></a>
	<%end%>
		<%=Usuario.find(user.idUsuario).alias%><%if user.admin=="true" or user.admin=="tru"%>(admin)<%end%>
		<%if user.admin=="false" and (grupo.admin=="true" or grupo.admin=="tru")%>
			(<a href="<%=darPermisos_path(:igu=>grupo.idGrupoUsuario,:iu=>user.idUsuario)%>">Dar Permisos</a>)
		<%end%>
		<%if user.admin=="tru" and grupo.admin=="true"%>
			(<a href="<%=quitarPermisos_path(:igu=>grupo.idGrupoUsuario,:iu=>user.idUsuario)%>">Quitar Permisos</a>)
		<%end%>
		<br />
	<%end%>
	<%if grupo.admin=="true" or grupo.admin=="tru"%>
	<a href="<%=addUserToGroup_path(grupo.idGrupoUsuario)%>"><i class="fa fa-plus-circle"></i>Añadir miembro al grupo</a>
	<%end%>
</p>

<table>
  <thead>
    <tr>
      <th style="border: black 1px solid;padding: 5px;">Nombre</th>
      <th style="border: black 1px solid;padding: 5px;">Tipo</th>
      <th style="border: black 1px solid;padding: 5px;">Descripcion</th>
      <th style="border: black 1px solid;padding: 5px;">Inicio</th>
      <th style="border: black 1px solid;padding: 5px;">Fin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyectos.each do |proyecto| %>
      <tr>
      	<%if proyecto.idUsuario== grupo.idGrupoUsuario%>
        <td style="border: black 1px solid;"><%= proyecto.nombre %></td>
        <td style="border: black 1px solid;"><%= proyecto.tipo %></td>
        <td style="border: black 1px solid;"><%= proyecto.descripcion %></td>
        <td style="border: black 1px solid;"><%= proyecto.inicio.to_s.split("-").reverse.join("/") %></td>
        <td style="border: black 1px solid;"><%= proyecto.fin.to_s.split("-").reverse.join("/") %></td>
        <td><%= link_to 'Show', proyecto %></td>
        <td><%= link_to 'Edit', edit_proyecto_path(proyecto) %></td>
        <%if grupo.admin=="true" or grupo.admin=="tru"%>
        <td><%= link_to 'Destroy', delProyecto_path(proyecto) %></td>
        <%end%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to nuevoProyecto_path(grupo.idGrupoUsuario)do%>
<i class="fa fa-plus"> Nuevo Proyecto</i>
<%end%>
</div>
					</section>
<%end%>
			</div>

	</body>
</html>

app/views/proyectos/new.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>Web de administracion y gestion de riesgos | Nuevo Proyecto</title>
		<% user @current_user %>
	</head>
	<body>
		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

							<header>
								<h2 class="alt">Nuevo proyecto de <%=@current_user["alias"]%></h2>
							</header>
						</div>
					</section>

				<!-- Portfolio -->
					<section id="top" class="two">
						<div class="container">
						
<%= render 'form' %>

<%= link_to 'Back', proyectos_path %>
</div>
					</section>

			</div>

	</body>
</html>

app/views/proyectos/show.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>Web de administracion y gestion de riesgos | Proyecto</title>
		<% user @current_user %>
	</head>
	<body>
		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

							<header>
								<h2 class="alt">Proyeto <%= @proyecto.id %>. <%= @proyecto.nombre %></h2>
							</header>
						</div>
					</section>

				<!-- Portfolio -->
					<section id="top" class="two">
						<div class="container">
						<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @proyecto.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @proyecto.tipo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @proyecto.descripcion %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= @proyecto.inicio.to_s.split("-").reverse.join("/") %>
</p>

<p>
  <strong>Fin:</strong>
  <%= @proyecto.fin.to_s.split("-").reverse.join("/") %>
</p>

<%= link_to 'Edit', edit_proyecto_path(@proyecto) %> |
<%= link_to 'Back', proyectos_path %>
<%=render template: "riesgos/index.html.erb"%>
<br /><hr /><br />
<div>SUGERENCIAS</div>
<table>
  <thead>
    <tr>
    	<th colspan="2"></th>
      <th style="border: black 1px solid;padding: 5px;">Nombre</th>
      <th style="border: black 1px solid;padding: 5px;">Probabilidad</th>
       <th style="border: black 1px solid;padding: 5px;">Impacto</th>
     <!-- <th style="border: black 1px solid;padding: 5px;">Categoria</th>
      <th style="border: black 1px solid;padding: 5px;">Tipo</th>
      <th style="border: black 1px solid;padding: 5px;">Descripcion</th>
      <th style="border: black 1px solid;padding: 5px;">Factores</th>
      <th style="border: black 1px solid;padding: 5px;">Reduccion</th>
      <th style="border: black 1px solid;padding: 5px;">Supervision</th>-->
      <th colspan="1"></th>
    </tr>
  </thead>
<%contador=0%>
<%add=0%>
  <tbody>
    <% @riesgos.where(:idUsuario=>Grupo.all.select(:idGrupoUsuario).where(:idUsuario=>@current_user["id"])).sort_by { |a| -(@riesgos.where(:idUsuario=>Grupo.all.select(:idGrupoUsuario).where(:idUsuario=>@current_user["id"])).group(:nombre).count[a.nombre] ) }.each do |riesgo| %>
      
      <tr>
      	
      	<%if riesgo.idProyecto!=@current_proyecto%>
      	<%if @riesgos.where(:idUsuario=>Proyecto.find(@current_proyecto).idUsuario).where(:idProyecto=>@current_proyecto).group(:nombre).count[riesgo.nombre]==nil%>
      	<%contador=contador+1%>
      	<td colspan="2"></td>
        <td style="border: black 1px solid;"><%= riesgo.nombre %></td>
        <td style="border: black 1px solid;"><%= riesgo.probabilidad %></td>
        <td style="border: black 1px solid;"><%= riesgo.impacto %></td>
        <!--<td style="border: black 1px solid;"><%= riesgo.categoria %></td>
        <td style="border: black 1px solid;"><%= riesgo.tipo %></td>
        <td style="border: black 1px solid;"><%= riesgo.descripcion %></td>
        <td style="border: black 1px solid;"><%= riesgo.factores %></td>
        <td style="border: black 1px solid;"><%= riesgo.reduccion %></td>
        <td style="border: black 1px solid;"><%= riesgo.supervision %></td>-->
        <td ><%= link_to 'Show', riesgo %></td>
        <td ><%= link_to 'Añadir', addRiesgo_path(riesgo.id) %></td>
      
        <%end%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
					</section>

			</div>

	</body>
</html>