config/routes.rb
Rails.application.routes.draw do
  resources :grupos
  resources :riesgos
  resources :categoria_riesgos
  resources :impacto_riesgos
  resources :tipo_proyectos
  resources :proyectos
  resources :usuarios
  
  root 'pages#home'
  post 'login' => 'pages#login'
  post 'recuperarPass' => 'pages#recuperarPass'
  get 'recuperar' => 'pages#recuperar'
  get 'correo'=> 'pages#correo'
  get 'registrarse' => 'pages#registrar'
  get 'salir' => 'pages#salir'
  get 'delTipoProyecto/:id'=> 'tipo_proyectos#destroy', as: :delTipoProyecto
  get 'delCategoriaRiesgos/:id'=> 'categoria_riesgos#destroy', as: :delCategoriaRiesgos
  get 'delImpactoRiesgos/:id'=> 'impacto_riesgos#destroy', as: :delImpactoRiesgos
  get 'delRiesgo/:id'=> 'riesgos#destroy', as: :delRiesgo
  get 'delProyecto/:id'=> 'proyectos#destroy', as: :delProyecto
  get 'subir' => 'proyectos#lineaCorteUp'
  get 'bajar' => 'proyectos#lineaCorteDown'
  get 'estadisticas' => 'pages#estadisticas'
  get 'add/:id'=>'riesgos#add', as: :addRiesgo
  get 'nuevoProyecto/:id'=> 'proyectos#new', as: :nuevoProyecto
  get 'delGrupo/:id'=> 'grupos#destroy', as: :delGrupo
  get 'addUserToGroup/:id'=>'pages#addUserToGroup', as: :addUserToGroup
  post 'addtog'=> 'pages#addtog'
  get 'darPermisos/:igu/:iu'=> 'pages#darPermisos', as: :darPermisos
  get 'quitarPermisos/:igu/:iu'=> 'pages#quitarPermisos', as: :quitarPermisos
  get 'del_user_grupo/:igu/:iu' => 'pages#del_user_grupo', as: :del_user_grupo
  get '*path' => redirect('/')

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  before_action :require_login
  before_action :set_grupo, only: [:show, :edit, :update]
    
  def require_login
     current_user
    unless @current_user!=nil
      redirect_to root_path
    end
  end
  # GET /grupos
  # GET /grupos.json
  def index
    current_user
    @grupos = Grupo.all
  end

  # GET /grupos/1
  # GET /grupos/1.json
  def show
    current_user
  end

  # GET /grupos/new
  def new
    @grupo = Grupo.new
    current_user
  end

  # GET /grupos/1/edit
  def edit
    current_user
  end

  # POST /grupos
  # POST /grupos.json
  def create
    current_user
    @grupo = Grupo.new(grupo_params)
    @grupo.idUsuario=@current_user["id"]
    @grupo.admin="true"
    grupo=@grupo
    respond_to do |format|
      if @grupo.save
        @grupo.idGrupoUsuario=@grupo.id
        @grupo.save
          tipoPro=TipoProyecto.new
        tipoPro.nombre="Software de Aplicaciones Web"
        tipoPro.idUsuario=grupo.idGrupoUsuario
        tipoPro.save
        impactoR=ImpactoRiesgo.new
        impactoR.nombre="Catastrófico"
        impactoR.idUsuario=grupo.idGrupoUsuario
        impactoR.ponderacion=100
        impactoR.save
         impactoR=ImpactoRiesgo.new
        impactoR.nombre="Crítico"
        impactoR.ponderacion=65
        impactoR.idUsuario=grupo.idGrupoUsuario
        impactoR.save
         impactoR=ImpactoRiesgo.new
        impactoR.nombre="Marginal"
        impactoR.ponderacion=35
        impactoR.idUsuario=grupo.idGrupoUsuario
        impactoR.save
         impactoR=ImpactoRiesgo.new
        impactoR.nombre="Despreciable"
        impactoR.ponderacion=10
        impactoR.idUsuario=grupo.idGrupoUsuario
        impactoR.save
        categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Planificación"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
         categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Organización y gestión"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
         categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Entorno de desarrollo"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
         categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Usuarios finales"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
         categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Cliente"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
         categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Personal contratado"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
         categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Requisitos"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
         categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Producto"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
        categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Fuerzas mayores"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
        categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Personal"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
        categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Diseño e implementación"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
        categoriaR=CategoriaRiesgo.new
        categoriaR.nombre="Proceso"
        categoriaR.idUsuario=grupo.idGrupoUsuario
        categoriaR.save
        format.html { redirect_to proyectos_path, notice: '' }
        format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos/1
  # PATCH/PUT /grupos/1.json
  def update
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to @grupo, notice: 'Grupo was successfully updated.' }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.json
  def destroy
    Grupo.all.where(:idGrupoUsuario=> params[:id]).destroy_all
    respond_to do |format|
      format.html { redirect_to proyectos_path, notice: '' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_params
      params.require(:grupo).permit(:idUsuario, :idGrupoUsuario,:nombre)
    end
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/grupos/_form.html.erb
<%= form_for(@grupo,:html=>{:onsubmit=>"return validacionGrupo();"}) do |f| %>
  <% if @grupo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupo.errors.count, "error") %> prohibited this grupo from being saved:</h2>

      <ul>
      <% @grupo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :nombre %><br>
    <%= f.text_field :nombre, :required=>true,:maxlength=>"255",:onkeyup=>"notNull(this);" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grupos/edit.html.erb
<h1>Editing Grupo</h1>

<%= render 'form' %>

<%= link_to 'Show', @grupo %> |
<%= link_to 'Back', grupos_path %>

app/views/grupos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grupos</h1>

<table>
  <thead>
    <tr>
      <th>Idusuario</th>
      <th>Idgrupousuario</th>
      <th>nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupos.each do |grupo| %>
      <tr>
        <td><%= grupo.idUsuario %></td>
        <td><%= grupo.idGrupoUsuario %></td>
        <td><%= grupo.nombre %></td>
        <td><%= link_to 'Show', grupo %></td>
        <td><%= link_to 'Edit', edit_grupo_path(grupo) %></td>
        <td><%= link_to 'Destroy', grupo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grupo', new_grupo_path %>

app/views/grupos/new.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>Web de administracion y gestion de riesgos | Nuevo Grupo</title>
		<% user @current_user %>
	</head>
	<body>
		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

							<header>
								<h2 class="alt">Crear Nuevo Grupo.</h2>
							</header>
						</div>
					</section>

				<!-- Portfolio -->
					<section id="top" class="two">
						<div class="container">
						
<%= render 'form' %>

<%= link_to 'Volver', proyectos_path %>
</div>
					</section>

			</div>

	</body>
</html>

app/views/grupos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idusuario:</strong>
  <%= @grupo.idUsuario %>
</p>

<p>
  <strong>Idgrupousuario:</strong>
  <%= @grupo.idGrupoUsuario %>
</p>

<%= link_to 'Edit', edit_grupo_path(@grupo) %> |
<%= link_to 'Back', grupos_path %>