config/routes.rb
Rails.application.routes.draw do
  resources :grupos
  resources :riesgos
  resources :categoria_riesgos
  resources :impacto_riesgos
  resources :tipo_proyectos
  resources :proyectos
  resources :usuarios
  
  root 'pages#home'
  post 'login' => 'pages#login'
  post 'recuperarPass' => 'pages#recuperarPass'
  get 'recuperar' => 'pages#recuperar'
  get 'correo'=> 'pages#correo'
  get 'registrarse' => 'pages#registrar'
  get 'salir' => 'pages#salir'
  get 'delTipoProyecto/:id'=> 'tipo_proyectos#destroy', as: :delTipoProyecto
  get 'delCategoriaRiesgos/:id'=> 'categoria_riesgos#destroy', as: :delCategoriaRiesgos
  get 'delImpactoRiesgos/:id'=> 'impacto_riesgos#destroy', as: :delImpactoRiesgos
  get 'delRiesgo/:id'=> 'riesgos#destroy', as: :delRiesgo
  get 'delProyecto/:id'=> 'proyectos#destroy', as: :delProyecto
  get 'subir' => 'proyectos#lineaCorteUp'
  get 'bajar' => 'proyectos#lineaCorteDown'
  get 'estadisticas' => 'pages#estadisticas'
  get 'add/:id'=>'riesgos#add', as: :addRiesgo
  get 'nuevoProyecto/:id'=> 'proyectos#new', as: :nuevoProyecto
  get 'delGrupo/:id'=> 'grupos#destroy', as: :delGrupo
  get 'addUserToGroup/:id'=>'pages#addUserToGroup', as: :addUserToGroup
  post 'addtog'=> 'pages#addtog'
  get 'darPermisos/:igu/:iu'=> 'pages#darPermisos', as: :darPermisos
  get 'quitarPermisos/:igu/:iu'=> 'pages#quitarPermisos', as: :quitarPermisos
  get 'del_user_grupo/:igu/:iu' => 'pages#del_user_grupo', as: :del_user_grupo
  get '*path' => redirect('/')

end

app/models/riesgo.rb
class Riesgo < ActiveRecord::Base
  validates :nombre , :tipo ,:probabilidad ,:categoria ,:impacto ,:factores ,:reduccion ,presence: true
end

app/controllers/riesgos_controller.rb
class RiesgosController < ApplicationController
before_action :require_login
  before_action :set_riesgo, only: [:show, :edit, :update, :destroy, :add]

  def require_login
     current_user
    unless @current_user!=nil
      redirect_to root_path
    end
  end
  # GET /riesgos
  # GET /riesgos.json
  def index
    current_user
    current_proyecto
    @riesgos = Riesgo.all
        @impacto_riesgos = ImpactoRiesgo.all
    @categoria_riesgos = CategoriaRiesgo.all
    
  end

  # GET /riesgos/1
  # GET /riesgos/1.json
  def show
    current_user
    current_proyecto
        @impacto_riesgos = ImpactoRiesgo.all
    @categoria_riesgos = CategoriaRiesgo.all
    @lineaCorte=Proyecto.find(@current_proyecto).lineaCorte
  end

  # GET /riesgos/new
  def new
    current_user
    current_proyecto
    @impacto_riesgos = ImpactoRiesgo.all
    @categoria_riesgos = CategoriaRiesgo.all
    @riesgo = Riesgo.new
  end

  # GET /riesgos/1/edit
  def edit
    current_user
    current_proyecto
    @impacto_riesgos = ImpactoRiesgo.all
    @categoria_riesgos = CategoriaRiesgo.all
  end

  # POST /riesgos
  # POST /riesgos.json
  def create
        @impacto_riesgos = ImpactoRiesgo.all
    @categoria_riesgos = CategoriaRiesgo.all
    current_user
    current_proyecto
    @riesgo = Riesgo.new(riesgo_params)
    @riesgo.idUsuario= Proyecto.find(@current_proyecto).idUsuario
    @riesgo.idProyecto=@current_proyecto
    if numeric(@riesgo.impacto)
    @riesgo.impacto=ImpactoRiesgo.find(@riesgo.impacto).nombre
    end
    if numeric(@riesgo.categoria)
    @riesgo.categoria=CategoriaRiesgo.find(@riesgo.categoria).nombre
    end
    respond_to do |format|
      if @riesgo.save
        format.html { redirect_to @riesgo, notice: '' }
        format.json { render :show, status: :created, location: @riesgo }
      else
        format.html { render :new }
        format.json { render json: @riesgo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /riesgos/1
  # PATCH/PUT /riesgos/1.json
  def numeric(s)
    Float(s) != nil rescue false
  end
  def update
        @impacto_riesgos = ImpactoRiesgo.all
    @categoria_riesgos = CategoriaRiesgo.all
    current_user
    current_proyecto
    respond_to do |format|
      riesgo=riesgo_params
      if numeric(riesgo[:impacto])
   riesgo[:impacto]=ImpactoRiesgo.find(riesgo_params[:impacto])[:nombre]
   end
   if numeric(riesgo[:categoria])
   riesgo[:categoria]=CategoriaRiesgo.find(riesgo_params[:categoria])[:nombre]
   end
      if @riesgo.update(riesgo)
        format.html { redirect_to @riesgo, notice: '' }
        format.json { render :show, status: :ok, location: @riesgo }
      else
        format.html { render :edit }
        format.json { render json: @riesgo.errors, status: :unprocessable_entity }
      end
    end
  end

def add
  current_user
    current_proyecto
    riesgo = Riesgo.new
    riesgo.nombre=@riesgo.nombre
    riesgo.categoria=@riesgo.categoria
    riesgo.impacto=@riesgo.impacto
    riesgo.tipo=@riesgo.tipo
    riesgo.probabilidad=@riesgo.probabilidad
    riesgo.descripcion=@riesgo.descripcion
    riesgo.factores=@riesgo.factores
    riesgo.reduccion=@riesgo.reduccion
    riesgo.supervision=@riesgo.supervision
    riesgo.idUsuario= @riesgo.idUsuario
    riesgo.idProyecto=@current_proyecto
    respond_to do |format|
      if riesgo.save
        format.html { redirect_to riesgo, notice: '' }
        format.json { render :show, status: :created, location: riesgo }
      else
        format.html { render :new }
        format.json { render json: riesgo.errors, status: :unprocessable_entity }
      end
    end
end
  # DELETE /riesgos/1
  # DELETE /riesgos/1.json
  def destroy
        @impacto_riesgos = ImpactoRiesgo.all
    @categoria_riesgos = CategoriaRiesgo.all
    current_user
    current_proyecto
    @riesgo.destroy

     @proyec=Proyecto.find(@current_proyecto)
     if @proyec.lineaCorte>Riesgo.all.where(:idUsuario=>@proyec.idUsuario).where(:idProyecto=>@proyec.id).count
    @proyec.lineaCorte=@proyec.lineaCorte.to_i-1
    @proyec.save   
      end

    respond_to do |format|
      format.html { redirect_to proyecto_path(@current_proyecto), notice: '' }
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_riesgo

      current_user
      if !numeric(params[:id])
        redirect_to root_path
      else
        aux=0
        Grupo.all.where(:idUsuario=> @current_user["id"]).each do |grupo|
        if Riesgo.all.where(:idUsuario=>grupo.idGrupoUsuario).where(:id=>params[:id]).count>0
       @riesgo = Riesgo.find(params[:id])
          aux=1
      end
      end
      if aux==0
        redirect_to root_path
      end
 end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def riesgo_params
      params.require(:riesgo).permit(:nombre, :categoria, :tipo, :impacto, :probabilidad, :descripcion, :factores, :reduccion, :supervision, :idProyecto, :idUsuario)
    end
end

app/helpers/riesgos_helper.rb
module RiesgosHelper
end

app/views/riesgos/_form.html.erb
<%= form_for(@riesgo, :html=>{:onsubmit=>"return validacionRiesgo();"}) do |f| %>
  <% if @riesgo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@riesgo.errors.count, "error") %> prohibited this riesgo from being saved:</h2>

      <ul>
      <% @riesgo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<style>
	form select{
	 height: 30px;
    padding: 0;
}
</style>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, :onkeyup=>"notNull(this);" %>
  </div>
  <div class="field" style="display: inline-block">
    <label for="riesgo_categoria">Categoria  <i class="fa fa-plus-circle fa-2x" onclick="document.getElementById('riesgo_categoria').disabled=false;if(document.getElementById('add1').style.display=='block'){document.getElementById('add1').style.display='none'}else{document.getElementById('add1').style.display='block';document.getElementById('edit1').style.display='none';}">
  
    </i> <i class="fa fa-pencil-square-o fa-2x" onclick="if(document.getElementById('riesgo_categoria').value!='Seleccione una categoria'){document.getElementById('edit1').src='/categoria_riesgos/'+document.getElementById('riesgo_categoria').value+'/edit'};if(document.getElementById('riesgo_categoria').value!='Seleccione una categoria'){if(document.getElementById('edit1').style.display=='block'){document.getElementById('edit1').style.display='none';document.getElementById('riesgo_categoria').disabled=false;}else{document.getElementById('edit1').style.display='block';document.getElementById('add1').style.display='none';document.getElementById('riesgo_categoria').disabled=true;}};"></i> 
    <i class="fa fa-times fa-2x" onclick="document.getElementById('riesgo_categoria').disabled=false;if(document.getElementById('riesgo_categoria').value!='Seleccione una categoria'){document.getElementById('add1').style.display='none';document.getElementById('edit1').style.display='none';$.ajax({
  url: '/delCategoriaRiesgos/'+document.getElementById('riesgo_categoria').value});var x = document.getElementById('riesgo_categoria');
    x.options[x.selectedIndex] =null};"></i></label> 
    
    <iframe id="add1" src="<%=new_categoria_riesgo_path%>" style="display:none;position: fixed; z-index: 99; background-color: rgba(172,220,218,1);border: solid 2px;border-radius: 20px;"></iframe><br>
    
    <iframe id="edit1" src="" style="display:none;position: fixed; z-index: 99; background-color: rgba(172,220,218,1);border: solid 2px;border-radius: 20px;"></iframe><br>
    
          <select name="riesgo[categoria]" id="riesgo_categoria" onclick="notNull(this);">
  <%= content_tag(:option, "Seleccione una categoria", value: "Seleccione una categoria") %>
  <% @categoria_riesgos.where(:idUsuario=>Grupo.all.select(:idGrupoUsuario).where(:idUsuario=>@current_user["id"])).group(:nombre).order(:nombre).each do |categoria_riesgo|%>

  <%if @riesgo.categoria.eql? categoria_riesgo.nombre%>
    <%= content_tag(:option, categoria_riesgo.nombre, value: categoria_riesgo.id, selected: true) %>
    <%else%>
    <%= content_tag(:option, categoria_riesgo.nombre, value: categoria_riesgo.id) %>
    <%end%>
    
  <% end %>
</select>
  </div>
  <div class="field" style="display: inline-block">
    <%= f.label :tipo %><br><br />
    <%= f.text_field :tipo, :onkeyup=>"notNull(this);"%>
  </div>
  <div class="field" style="display: inline-block">
    <label for="riesgo_impacto">Impacto  <i class="fa fa-plus-circle fa-2x" onclick="document.getElementById('riesgo_impacto').disabled=false;if(document.getElementById('add').style.display=='block'){document.getElementById('add').style.display='none'}else{document.getElementById('add').style.display='block';document.getElementById('edit').style.display='none';}">
  
    </i> <i class="fa fa-pencil-square-o fa-2x" onclick="if(document.getElementById('riesgo_impacto').value!='Seleccione un impacto'){document.getElementById('edit').src='/impacto_riesgos/'+document.getElementById('riesgo_impacto').value+'/edit'};if(document.getElementById('riesgo_impacto').value!='Seleccione un impacto'){if(document.getElementById('edit').style.display=='block'){document.getElementById('edit').style.display='none';document.getElementById('riesgo_impacto').disabled=false;}else{document.getElementById('edit').style.display='block';document.getElementById('add').style.display='none';document.getElementById('riesgo_impacto').disabled=true;}};"></i> 
    <i class="fa fa-times fa-2x" onclick="document.getElementById('riesgo_impacto').disabled=false;if(document.getElementById('riesgo_impacto').value!='Seleccione un impacto'){document.getElementById('edit').style.display='none';document.getElementById('add').style.display='none';$.ajax({
  url: '/delImpactoRiesgos/'+document.getElementById('riesgo_impacto').value});var x = document.getElementById('riesgo_impacto');
    x.options[x.selectedIndex] =null};"></i></label> 
    
    <iframe id="add" src="<%=new_impacto_riesgo_path%>" style="height: 190px;display:none;position: fixed; z-index: 99; background-color: rgba(172,220,218,1);border: solid 2px;border-radius: 20px;"></iframe><br>
    
    <iframe id="edit" src="" style="height: 190px;display:none;position: fixed; z-index: 99; background-color: rgba(172,220,218,1);border: solid 2px;border-radius: 20px;"></iframe><br>
    
     <select name="riesgo[impacto]" id="riesgo_impacto" onclick="notNull(this);">
  <%= content_tag(:option, "Seleccione un impacto", value: "Seleccione un impacto") %>
  <% @impacto_riesgos.where(:idUsuario=>Grupo.all.select(:idGrupoUsuario).where(:idUsuario=>@current_user["id"])).group(:nombre).order(ponderacion: :desc).each do |impacto_riesgo|%>

  <%if @riesgo.impacto.eql? impacto_riesgo.nombre%>
    <%= content_tag(:option, impacto_riesgo.nombre, value: impacto_riesgo.id, selected: true) %>
    <%else%>
    <%= content_tag(:option, impacto_riesgo.nombre, value: impacto_riesgo.id) %>
    <%end%>
    
  <% end %>
</select>
  </div>
  <div class="field" style="display: inline-block">
    <%= f.label :probabilidad %><br><br />
     <%= f.select(:probabilidad) do %>
     <%
 contador = 0;
 limite = 100;
%>
<% while contador < limite %>
   <% contador += 0.5; %>
   <%if @riesgo.probabilidad!=nil and @riesgo.probabilidad.to_d==contador%>
    <%= content_tag(:option, contador.to_s+"%", value: contador, selected: true ) %>
    <%else%>
    <%= content_tag(:option, contador.to_s+"%", value: contador) %>
    <%end%>
  <% end %>
<% end %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :factores %><br>
    <%= f.text_area :factores,:onkeyup=>"notNull(this);" %>
  </div>
  <div class="field">
    <%= f.label :reduccion %><br>
    <%= f.text_area :reduccion, :onkeyup=>"notNull(this);" %>
  </div>
  <div class="field">
    <%= f.label :supervision %><br>
    <%= f.text_area :supervision %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
	<script>
        function tlp() {
            $('.tooltip').tooltipster({
            	contentAsHTML: true//,
   //trigger: 'click'
            });
        }
         window.onload = tlp;
         
         
    </script>

app/views/riesgos/edit.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>Web de administracion y gestion de riesgos | Proyecto</title>
		<% user @current_user %>
	</head>
	<body>
		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

							<header>
								<h2 class="alt">Editar Riesgo <%= @riesgo.id %>. <%= @riesgo.nombre %></h2>
							</header>
						</div>
					</section>

				<!-- Portfolio -->
					<section id="top" class="two">
						<div class="container">
						<%= render 'form' %>

<%= link_to 'Show', @riesgo %> |
<%= link_to 'Back', proyecto_path(@current_proyecto) %>
</div>
					</section>

			</div>

	</body>
</html>

app/views/riesgos/index.html.erb
<h1>Lista de Riesgos</h1>

<table>
  <thead>
    <tr>
    	<th colspan="2"></th>
      <th style="border: black 1px solid;padding: 5px;">Nombre</th>
      <th style="border: black 1px solid;padding: 5px;">Probabilidad</th>
       <th style="border: black 1px solid;padding: 5px;">Impacto</th>
     <!-- <th style="border: black 1px solid;padding: 5px;">Categoria</th>
      <th style="border: black 1px solid;padding: 5px;">Tipo</th>
      <th style="border: black 1px solid;padding: 5px;">Descripcion</th>
      <th style="border: black 1px solid;padding: 5px;">Factores</th>
      <th style="border: black 1px solid;padding: 5px;">Reduccion</th>
      <th style="border: black 1px solid;padding: 5px;">Supervision</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>
<%contador=0%>
<%add=0%>
  <tbody>
    <% @riesgos.where(:idUsuario=>Proyecto.find(@current_proyecto).idUsuario).sort_by { |a| -(Float(a.probabilidad)*Float(ImpactoRiesgo.all.where(:idUsuario=>Proyecto.find(@current_proyecto).idUsuario).where(:nombre=>a.impacto).first["ponderacion"])) }.each do |riesgo| %>
      
      <tr>
      	<%if riesgo.idProyecto==@current_proyecto%>
      	<%contador=contador+1%>
      	<td colspan="2"></td>
        <td style="border: black 1px solid;"><%= riesgo.nombre %></td>
        <td style="border: black 1px solid;"><%= riesgo.probabilidad %></td>
        <td style="border: black 1px solid;"><%= riesgo.impacto %></td>
        <!--<td style="border: black 1px solid;"><%= riesgo.categoria %></td>
        <td style="border: black 1px solid;"><%= riesgo.tipo %></td>
        <td style="border: black 1px solid;"><%= riesgo.descripcion %></td>
        <td style="border: black 1px solid;"><%= riesgo.factores %></td>
        <td style="border: black 1px solid;"><%= riesgo.reduccion %></td>
        <td style="border: black 1px solid;"><%= riesgo.supervision %></td>-->
        <td ><%= link_to 'Show', riesgo %></td>
        <td ><%= link_to 'Edit', edit_riesgo_path(riesgo) %></td>
        <td ><%= link_to 'Destroy',delRiesgo_path(riesgo) %></td>
        <%end%>
      </tr>
      
          <%if contador==@lineaCorte and add==0%>
          <%add=1%>
    <tr>
    	<%if @lineaCorte>1%>
    	<td style="font-size: x-large;"><%= link_to subir_path do %><i class="fa fa-arrow-circle-up" style="color: rebeccapurple;"></i><%end%></td>
    	<%else%>
    	<td></td>
    	<%end%>
    	<%if @riesgos.where(:idProyecto => @current_proyecto).count > @lineaCorte%>
    	<td style="font-size: x-large;"><%= link_to bajar_path do %><i class="fa fa-arrow-circle-down" style="color: rebeccapurple;"></i><%end%></td>
    	<%else%>
    	<td></td>
    	<%end%>
    	<td colspan="3" style="background: yellow;font-size: x-large;border: black 1px solid;">---------------Linea de corte---------------</td>
    	
    </tr>
    <%end%>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Riesgo', new_riesgo_path %>

app/views/riesgos/new.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>Web de administracion y gestion de riesgos | Proyecto</title>
		<% user @current_user %>
	</head>
	<body>
		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

							<header>
								<h2 class="alt">Nuevo Riesgo</h2>
							</header>
						</div>
					</section>

				<!-- Portfolio -->
					<section id="top" class="two">
						<div class="container">
<%= render 'form' %>
<%= link_to 'Back', proyecto_path(@current_proyecto) %>
</div>
					</section>

			</div>

	</body>
</html>

app/views/riesgos/show.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>Web de administracion y gestion de riesgos | Proyecto</title>
		<% user @current_user %>
	</head>
	<body>
		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

							<header>
								<h2 class="alt">Información Riesgo <%= @riesgo.id %>. <%= @riesgo.nombre %></h2>
							</header>
						</div>
					</section>

				<!-- Portfolio -->
					<section id="top" class="two">
						<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @riesgo.nombre %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @riesgo.categoria %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @riesgo.tipo %>
</p>

<p>
  <strong>Impacto:</strong>
  <%= @riesgo.impacto %>
</p>

<p>
  <strong>Probabilidad:</strong>
  <%= @riesgo.probabilidad %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @riesgo.descripcion %>
</p>

<p>
  <strong>Factores:</strong>
  <%= @riesgo.factores %>
</p>

<p>
  <strong>Reduccion:</strong>
  <%= @riesgo.reduccion %>
</p>

<p>
  <strong>Supervision:</strong>
  <%= @riesgo.supervision %>
</p>

<%= link_to 'Edit', edit_riesgo_path(@riesgo) %> |
<%= link_to 'Back', proyecto_path(@current_proyecto) %>
</div>
					</section>

			</div>

	</body>
</html>