config/routes.rb
Rails.application.routes.draw do
  resources :grupos
  resources :riesgos
  resources :categoria_riesgos
  resources :impacto_riesgos
  resources :tipo_proyectos
  resources :proyectos
  resources :usuarios
  
  root 'pages#home'
  post 'login' => 'pages#login'
  post 'recuperarPass' => 'pages#recuperarPass'
  get 'recuperar' => 'pages#recuperar'
  get 'correo'=> 'pages#correo'
  get 'registrarse' => 'pages#registrar'
  get 'salir' => 'pages#salir'
  get 'delTipoProyecto/:id'=> 'tipo_proyectos#destroy', as: :delTipoProyecto
  get 'delCategoriaRiesgos/:id'=> 'categoria_riesgos#destroy', as: :delCategoriaRiesgos
  get 'delImpactoRiesgos/:id'=> 'impacto_riesgos#destroy', as: :delImpactoRiesgos
  get 'delRiesgo/:id'=> 'riesgos#destroy', as: :delRiesgo
  get 'delProyecto/:id'=> 'proyectos#destroy', as: :delProyecto
  get 'subir' => 'proyectos#lineaCorteUp'
  get 'bajar' => 'proyectos#lineaCorteDown'
  get 'estadisticas' => 'pages#estadisticas'
  get 'add/:id'=>'riesgos#add', as: :addRiesgo
  get 'nuevoProyecto/:id'=> 'proyectos#new', as: :nuevoProyecto
  get 'delGrupo/:id'=> 'grupos#destroy', as: :delGrupo
  get 'addUserToGroup/:id'=>'pages#addUserToGroup', as: :addUserToGroup
  post 'addtog'=> 'pages#addtog'
  get 'darPermisos/:igu/:iu'=> 'pages#darPermisos', as: :darPermisos
  get 'quitarPermisos/:igu/:iu'=> 'pages#quitarPermisos', as: :quitarPermisos
  get 'del_user_grupo/:igu/:iu' => 'pages#del_user_grupo', as: :del_user_grupo
  get '*path' => redirect('/')

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= csrf_meta_tags %>
</head>
<style>
	.colorEmail{
		color: whitesmoke;
	}
	.colorRecuperar{
		color: whitesmoke;
	}
</style>
<body>
	<!-- Header -->
			<div id="header">

				<div class="top">

					<!-- Logo -->
						<div id="logo">
							<%if yield(:user)!=""%>
							<h1 id="title">Bienvenido <%=yield(:username)%> ! | <%= link_to salir_path do%><i class="fa fa-sign-out"></i><%end%></h1>
							<%end%>
						<%if yield(:user)==""%>	
		<%= form_for(yield(:user), url: login_path) do |f| %>
			<input type="text" name="usuario[usernameLogin]" id="usuario_usernameLogin" required placeholder="Username" autocomplete="off" maxlength="255">
			<input type="password" name="usuario[passwordLogin]" id="usuario_passwordLogin" required placeholder="Password" autocomplete="off">
			<%= link_to "Registrarse", new_usuario_path, :class => "colorEmail"%>	 <%=f.submit "Login"%>
		<%end%><br />
		<%= link_to "¿He olvidado mi contraseña?", recuperar_path, :class=> "colorRecuperar"%>		<%end%>
							
						</div>

					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li>
									<%= link_to root_path, class: "skel-layers-ignoreHref" do%>
									<span class="icon fa-home">Inicio</span>
									<%end%>
								</li>
								<%if yield(:user)!=""%>
								<li>
									<%= link_to proyectos_path, class: "skel-layers-ignoreHref" do%>
									<span class="icon fa-th">Mis Proyectos</span>
									<%end%>
								</li>
								<li>
									<%= link_to usuario_path(yield(:iduser)), class: "skel-layers-ignoreHref" do%>
									<span class="icon fa-user">Mis datos</span>
									<%end%>
								</li>
								<li>
									<%= link_to estadisticas_path, class: "skel-layers-ignoreHref" do%>
									<span class="icon fa-bar-chart">Mis estadísticas</span></a></li>
									<%end%>
								<%end%>
								<br />
								
								<center><li><hr>Enlaces Relacionados<hr>
								<ul>
									<li><a href="http://es.slideshare.net/jes4791/ingenieria-del-software-un-enfoque-practico" target="_blank" class="skel-layers-ignoreHref">Ing. Software - Pressman</a></li>
									<li><a href="http://zeus.inf.ucv.cl/~bcrawford/Modelado%20UML/Ingenieria%20del%20Software%207ma.%20Ed.%20-%20Ian%20Sommerville.pdf" target="_blank"  class="skel-layers-ignoreHref">Ing. Software - Sommerville</a></li>
									<li><a href="http://www.sei.cmu.edu/reports/96tr012.pdf" target="_blank" class="skel-layers-ignoreHref">SEI.Soft Risk Management</a></li>
								</ul></li></center>
								
							</ul>
						</nav>

				</div>

				

			</div>

<%= yield %>
<!-- Footer -->
<div id="main">
			<div id="footer" style="margin-left: 0px;">

				<!-- Copyright -->
					<ul class="copyright">
						<li>2015 &copy; Equipo 06. All rights reserved.</li>
					</ul>

			</div>
</div>
		<!-- Scripts -->

  <%= javascript_include_tag 'jquery.min', :type => "text/javascript" %>
  <%= javascript_include_tag 'jquery.scrolly.min', :type => "text/javascript" %>
  <%= javascript_include_tag 'jquery.scrollzer.min', :type => "text/javascript" %>
  <%= javascript_include_tag 'skel.min', :type => "text/javascript" %>
  <%= javascript_include_tag 'util', :type => "text/javascript" %>
  <%= javascript_include_tag 'main', :type => "text/javascript" %>
  <%= javascript_include_tag 'jquery.tooltipster.min', :type => "text/javascript" %>
</body>
</html>